from matplotlib import animation
from matplotlib import pyplot as plt
from random import randint
import argparse
import math
import numpy as np

# Marshaller text file parser.
class Parser(object):
    def __init__(self, filename):
        self.f = open(filename, "r")
        self.n = int(self.f.readline())
        self.L = float(self.f.readline())
        self.N = int(self.f.readline())
        self.N_p = int(self.f.readline())
        self.masses = [float(self.f.readline()) for _ in range(self.N_p)]

    def parse(self):
        """Parses (positions, velocities)"""
        positions = []
        velocities = []
        for _ in range(self.N_p):
            x, y, vx, vy = [float(_) for _ in self.f.readline().split()]
            positions.append((x, y))
            velocities.append((vx, vy))
        return (positions, velocities)

def black(n, m):
    """
    Returns a n by m RGBA numpy array where each pixel is black with 100%
    opacity.
    """
    a = np.zeros((n, m, 4))
    a[:,:,3] += 1
    return a

def render(points, a):
    """
    Given a list of (x, y) coordinates (`points`) and a numpy array (`a`)
    decrease the opacity of a[x, y] for each (x, y) in `points`. This has the
    effect of whitening the position of each particle. If multiple particles
    overlap, the position becomes whiter. It is a precondition that all (x, y)
    coordinates are within `a`.
    """
    dalpha = 0.5
    for (x, y) in points:
        a[x,y,3] = min(a[x,y,3] - dalpha, 1)

def random_velocity():
    v = 2
    return (randint(-v, v), randint(-v, v))

def main(args):
    parser = Parser(args.filename)
    fps = 30                 # frames per second
    frames = parser.n        # number of mp4 frames
    n = math.ceil(parser.L)  # height (n) of mp4 in pixels
    m = n                    # width (n)  of mp4 in pixels
    nparticles = parser.N_p  # number of particles

    fig = plt.figure()
    im = plt.imshow(black(n, m), interpolation="none")

    def init():
        a = black(n, m)
        im.set_array(a)
        return [im]

    def animate(i):
        (pos, _) = parser.parse()
        a = black(n, m)
        render(pos, a)
        im.set_array(a)
        return [im]

    anim = animation.FuncAnimation(fig, animate, init_func=init,
                                   frames=frames, blit=True)
    anim.save('particles.mp4', fps=fps)

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("filename", help="Text file generated by marshaller.cpp")
    return parser.parse_args()

if __name__ == "__main__":
    main(parse_args())
