import argparse

def renderer_args(parser):
    parser.add_argument(
        "-p", "--pixels",
        type=int,
        default=100,
        help="side length of mp4 in pixels"
    )
    parser.add_argument(
        "-f", "--fps",
        type=int,
        default=30,
        help="frames per second"
    )
    parser.add_argument(
        "-m", "--mass",
        type=int,
        default=4,
        help="the amount of mass to make a pixel compeltely white"
    )

def file_args(parser):
    parser.add_argument(
        "filename",
        help="text file generated by marshaller.cpp"
    )

def net_args(parser):
    parser.add_argument(
        "host",
        help="host name of particle simulator"
    )
    parser.add_argument(
        "port",
        type=int,
        help="port number of particle simulator"
    )
