import argparse

def parser():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()

    # common arguments
    parser.add_argument(
        "-p", "--pixels",
        type=int,
        default=100,
        help="side length of mp4 in pixels"
    )
    parser.add_argument(
        "-f", "--fps",
        type=int,
        default=30,
        help="frames per second"
    )
    parser.add_argument(
        "-m", "--mass",
        type=int,
        default=4,
        help="the amount of mass to make a pixel compeltely white"
    )

    # file parser
    fileparser = subparsers.add_parser('file', help="file parser")
    fileparser.add_argument(
        "filename",
        help="text file generated by marshaller.cpp"
    )

    # net parser
    netparser = subparsers.add_parser('net', help="network parser")
    netparser.add_argument(
        "host",
        help="host name of particle simulator"
    )
    netparser.add_argument(
        "port",
        type=int,
        help="port number of particle simulator"
    )

    return parser

