from parser import FileParser
from random import randint
from renderer import Renderer
import argparse
import math
import moviepy.editor as mpy
import numpy as np

def main(args):
    parser = FileParser(args.filename)
    renderer = Renderer(args.pixels, args.mass, parser)

    fps = args.fps                    # frames per second
    frames = parser.n                 # number of mp4 frames
    duration = float(frames) / fps    # duration of mp4 in seconds
    nparticles = parser.N_p + 1       # number of particles

    clip = mpy.VideoClip(lambda _: renderer.next(), duration=duration)
    clip.write_videofile("particles.mp4", fps=fps)

def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "filename",
        help="text file generated by marshaller.cpp"
    )
    parser.add_argument(
        "-p", "--pixels",
        type=int,
        default=100,
        help="side length of mp4 in pixels"
    )
    parser.add_argument(
        "-f", "--fps",
        type=int,
        default=30,
        help="frames per second"
    )
    parser.add_argument(
        "-m", "--mass",
        type=int,
        default=4,
        help="the amount of mass to make a pixel compeltely white"
    )

    return parser.parse_args()

if __name__ == "__main__":
    main(parse_args())
